### ISSUE TITLE
Installation instructions missing

### ISSUE THREAD

**Issue by jonnor** [uio-bmi/dagsim#8]
Hi, I saw the presentation at NORA Annual Conference, and checked out the project.

I do not see any installation instructions in either the README, or in the documentation page (https://uio-bmi.github.io/dagsim/)

I also did not find dagsim on PyPI. Would recommend putting the module on there and have it installable from there.
And to have those instructions and a super trivial example in the README (and the docs).

**Comment by ghadialhajj** [comment]
Hi, thank you for your interest and for your suggestions. That is true, DagSim is still not published on PyPI but I will do that soon. 

In the meantime, please consider trying DagSim in a binder session (by pressing the "launch binder" badge on the front page). There you can find a pre-set Jupyter notebook with a simple example of simulating data using DagSim :)

**Comment by ghadialhajj** [comment]
The module is now on PyPI and can be installed using pip. Thank you for your suggestions.
